export EDITOR='vim'
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="af-magic"
plugins=(git aws zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

if [ -r ~/.aliases ]; then
  source ~/.aliases
fi
