# Set default editor
export EDITOR=vim

# Source aliases if exists
if [ -r ~/.aliases ]; then
  source ~/.aliases
fi

if [ -r ~/.bashrc ]; then
  source ~/.bashrc
fi

# Terminal colors
export CLICOLOR=1

if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
  GIT_PROMPT_THEME=Default
  source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
fi

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  source $(brew --prefix)/etc/bash_completion
fi

# iTerm shell integration
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
